name: example-environment
#channels:
  #- conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - squarify
  - plotly
  - itables
  - python=3.11
  - sqlalchemy
  - @8080labs/qgrid
  #- qgrid==1.1.1
  #- PandasGUI
  #- tabloo
  #- dtale
  - datapane
  - pivottablejs
