name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - entrypoints
  #- jsonschema
  - six
  - typing
  - ipython
  - altair>=2.2.0
  - vega_datasets
  - jupyterlab>=0.32.0
