name: example-environment
#channels:
  #- conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - squarify
  - plotly
  - itables
  - python=3.11
  - sqlalchemy

