name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - squarify
  - plotly
  - itables
#  - python=3.11
  - python
  - sqlalchemy
  #- qgrid==1.1.1
  #- PandasGUI
  #- tabloo
  #- dtale
  #- jupyter_Pandas_GUI
  #- Pandas_ui
  - pandasgui
  - datapane
  - pivottablejs
  - jupyterlab
  - qgrid
  - pandas-datareader>=0.5.0
  - matplotlib>=2.1.1
  #- altair
  #- bokeh
  #- folium
  #- ipywidgets
  #- jupytext
  #- matplotlib
  - nbclient
  #- numpy
  #- pandas
  #- plotly
  #- sphinx-click
  #- sphinx-examples
  #- sphinx_inline_tabs
  #- sphinx-proof
  #- sphinxext-rediraffe~=0.2.3
  #- sympy
